version: '3'
services: 
    elasticsearch:
        container_name: 'elasticsearch'
        image: 'elasticsearch:7.8.0'
        ports: 
            - "9200:9200"
            - "9300:9300"
        environment: 
            - discovery.type=single-node
        